var citiesDB = {cities:new ko.observableArray( [{ name:"AGRA",value:"AGRA",state:"UTTAR PRADESH",storelocations:[]},
{ name:"AHMADNAGAR",value:"AHMADNAGAR",state:"MAHARASHTRA",storelocations:[]},
{ name:"AHMEDABAD",value:"AHMEDABAD",state:"GUJARAT",storelocations:[]},
{ name:"AJMER",value:"AJMER",state:"RAJASTHAN",storelocations:[]},{ name:"ALLAHABAD",value:"ALLAHABAD", state:"UTTAR PRADESH",storelocations:[]},
{ name:"AMRITSAR",value:"AMRITSAR",state:"PUNJAB",storelocations:[]},{ name:"ANAND",value:"ANAND",state:"GUJARAT",storelocations:[]},
{ name:"ASANSOL",value:"ASANSOL", state:"WEST BENGAL",storelocations:[]},{ name:"AURANGABAD",value:"AURANGABAD",state:"MAHARASHTRA",storelocations:[]},
{ name:"BADDI",value:"BADDI",state:"KARNATAKA",storelocations:[]},{ name:"BANGALORE",value:"BANGALORE",state:"KARNATAKA",
storelocations:[{name:"AIRPORT ROAD"},{name:"ASCENDAS PARK SQUARE"},{name:"BANERGHATTA ROAD"},{name:"BANGALORE CENTRAL"},
                {name:"BANSHANKARI"},{name:"BASAVESWARANAGAR"},{name:"BEGUR HOBLI HOSUR ROAD"},{name:"BELLANDUR VILLAGE"},
                {name:"BOMMASANDRA"},{name:"BRIGADE METROPOLIS MAHADEVPURA"},{name:"BROOKEFIELD"},
                {name:"BTM LAYOUT"},
                {name:"Bellandur"},
                {name:"BULL TEMPLE ROAD BASVANGUDI"},
                {name:"CAMBRIDGE ROAD"},{name:"CHANDRA LAYOUT"},
                {name:"CHIKKALASANDRA  UTTRAHALLI "},
                {name:"COLES ROAD"},{name:"UNNINGHAM"},
                {name:"CV RAMAN NAGAR "},{name:"EGL DOMLUR "},
                {name:"ELECTRONIC CITY"},{name:"ELECTRONIC CITY 2"},
                {name:"GOPALAN MALL"},{name:"HENNUR VILLAGE"},
                {name:"HORAMAVU VILLAGE"},{name:"HRBR LAYOUT"},
                {name:"HSR LAYOUT"},{name:"NDIRA NAGAR"},{name:"J P  NAGAR"},
                {name:"AYANAGAR"},{name:"KANCHANHALLI"},
                {name:"KASTURI NAGAR"},{name:"KORAMANGLA"},
                {name:"KRISHNA NAGAR"},{name:"MALLESHWARAM"},
                {name:"MANYATA TECH PARK RACHENEHALLI"},
                {name:"MARATHALLI"},
                {name:"NEW BEL ROAD"},
                {name:"OUTER RING ROAD"},
                {name:"EX THEATER"},
                {name:"RICHMOND TOWN"},{name:"RMZ ECOSPACE"},
                {name:"RT NAGAR"},{name:"SARJAPUR ROAD"},
                {name:"SJR I PARK"},{name:"SOUL SPACE DODDANEKKUNDI"},
                {name:"STAR BAZAAR RAJAJI NAGAR BANGALORE"},
                {name:"VIDYANARAYANA PURA"},{name:"WHITE FIELD  RAMAGONDANAHALLI"},
                {name:"YELACHENAHALLI KANAKPURA ROAD "},
                {name:"YELAHANKA HOBLI "},{name:"YELAHANKA SATELLITE TOWN"}]

},
{ name:"BAREILLY",value:"BAREILLY",state:"UTTAR PRADESH",storelocations:[]},{ name:"BHATINDA",value:"BHATINDA",state:"PUNJAB",storelocations:[]},
{ name:"BHAVNAGAR",value:"BHAVNAGAR",state:"GUJARAT",storelocations:[]},{ name:"BHILAI",value:"BHILAI",state:"MADHYA PRADESH",storelocations:[]},
{ name:"BHOPAL",value:"BHOPAL",state:"MADHYA PRADESH",storelocations:[]},{ name:"BHUWANESHWAR",value:"BHUWANESHWAR",state:"Orrisa",storelocations:[]},
{ name:"BILASPUR",value:"BILASPUR",state:"MADHYA PRADESH",storelocations:[]},{ name:"BURDWAN",value:"BURDWAN", state:"WEST BENGAL",storelocations:[]},
{ name:"CALICUT",value:"CALICUT",state:"KERALA",storelocations:[]},{ name:"CHANDIGARH",value:"CHANDIGARH",state:"PUNJAB",storelocations:[]},
{ name:"CHENNAI",value:"CHENNAI",state:"TAMIL NADU",storelocations:[]},{ name:"COCHIN",value:"COCHIN",state:"KERALA",storelocations:[]},
{ name:"COIMBATORE",value:"COIMBATORE",state:"TAMIL NADU",storelocations:[]},{ name:"DAMAN",value:"DAMAN",state:"DIU & DAMAN",storelocations:[]},
{ name:"DEHRADUN",value:"DEHRADUN",state:"UTTARAKHAND",storelocations:[]},{ name:"DHANBAD",value:"DHANBAD",state:"JHARKHAND",storelocations:[]},
{ name:"FARIDABAD",value:"FARIDABAD",state:"HARYANA",storelocations:[]},{ name:"GANDHIDHAM",value:"GANDHIDHAM",state:"GUJARAT",storelocations:[]},
{ name:"Ghaziabad",value:"Ghaziabad",state:"UTTAR PRADESH",storelocations:[]},{ name:"GREATER NOIDA",value:"GREATER NOIDA",state:"UTTAR PRADESH",storelocations:[]},
{ name:"GULBARGA",value:"GULBARGA",state:"KARNATAKA",storelocations:[]},{ name:"GURGAON",value:"GURGAON",state:"HARYANA",storelocations:[]},
{ name:"GUWAHATI",value:"GUWAHATI",state:"ASSAM"},{ name:"GWALIOR",value:"GWALIOR",state:"MADHYA PRADESH"},
{ name:"HARIDWAR",value:"HARIDWAR",state:"UTTARAKHAND",storelocations:[]},{ name:"HOWRAH",value:"HOWRAH",state:"WEST BENGAL",storelocations:[]},
{ name:"HYDERABAD",value:"HYDERABAD",state:"ANDHRA PRADESH",storelocations:[]},{ name:"INDORE",value:"INDORE",state:"MADHYA PRADESH",storelocations:[]},
{ name:"JABALPUR",value:"JABALPUR",state:"MADHYA PRADESH",storelocations:[]},{ name:"JAIPUR",value:"JAIPUR",state:"RAJASTHAN",storelocations:[]},
{ name:"JALGAON",value:"JALGAON",state:"MAHARASHTRA",storelocations:[]},{ name:"JALLANDHAR",value:"JALLANDHAR",state:"PUNJAB",storelocations:[]},
{ name:"JAM NAGAR",value:"JAM NAGAR",state:"GUJARAT",storelocations:[]},{ name:"JAMMU",value:"JAMMU",state:"JAMMU & KASHMIR"},
{ name:"JAMSHEDPUR",value:"JAMSHEDPUR",state:"JHARKHAND"},{ name:"KANPUR",value:"KANPUR",state:"UTTAR PRADESH",storelocations:[]},
{ name:"KARNAL",value:"KARNAL",state:"HARYANA",storelocations:[]},{ name:"KOHLAPUR",value:"KOHLAPUR",state:"MAHARASHTRA",storelocations:[]},
{ name:"KOLKATTA",value:"KOLKATTA",state:"WEST BENGAL",storelocations:[]},{ name:"KOTA",value:"KOTA",state:"RAJASTHAN",storelocations:[]},
{ name:"KURUKSHETRA",value:"KURUKSHETRA",state:"HARYANA",storelocations:[]},{ name:"LONAVALA",value:"LONAVALA",state:"MAHARASHTRA",storelocations:[]},
{ name:"LUCKNOW",value:"LUCKNOW",state:"UTTAR PRADESH",storelocations:[]},{ name:"LUDHIANA",value:"LUDHIANA",state:"PUNJAB",storelocations:[]},
{ name:"MADURAI",value:"MADURAI",state:"TAMIL NADU",storelocations:[]},{ name:"MAHABALESHWAR",value:"MAHABALESHWAR",state:"MAHARASHTRA",storelocations:[]},
{ name:"MANGALORE",value:"MANGALORE",state:"KARNATAKA",storelocations:[]},{ name:"MANIPAL",value:"MANIPAL",state:"KARNATAKA",storelocations:[]},
{ name:"MEERUT",value:"MEERUT",state:"UTTAR PRADESH",storelocations:[]},{ name:"MOHALI",value:"MOHALI",state:"PUNJAB",storelocations:[]},
{ name:"MUMBAI",value:"MUMBAI",state:"MAHARASHTRA",storelocations:[]},{ name:"MUSSOORIE",value:"MUSSOORIE",state:"UTTARAKHAND",storelocations:[]},
{ name:"MYSORE",value:"MYSORE",state:"KARNATAKA",storelocations:[]},{ name:"NAGPUR",value:"NAGPUR",state:"MAHARASHTRA",storelocations:[]},
{ name:"NASIK",value:"NASIK",state:"MAHARASHTRA",storelocations:[]},{ name:"NAVI MUMBAI",value:"NAVI MUMBAI",state:"MAHARASHTRA",storelocations:[]},
{ name:"NEW DELHI",value:"NEW DELHI",state:"DELHI",storelocations:[]},{ name:"NOIDA",value:"NOIDA",state:"UTTAR PRADESH",storelocations:[]},
{ name:"OOTY",value:"OOTY",state:"TAMIL NADU",storelocations:[]},{ name:"PANCHKULA",value:"PANCHKULA",state:"HARYANA",storelocations:[]},
{ name:"PANIPAT",value:"PANIPAT",state:"HARYANA",storelocations:[]},{ name:"PATIALA",value:"PATIALA",state:"PUNJAB",storelocations:[]},
{ name:"PATNA",value:"PATNA",state:"BIHAR",storelocations:[]},{ name:"PUNE",value:"PUNE",state:"MAHARASHTRA",storelocations:[]},
{ name:"PURI",value:"PURI",state:"ORISSA",storelocations:[]},{ name:"RAIPUR",value:"RAIPUR",state:"CHHATTISGAHR",storelocations:[]},
{ name:"RAJKOT",value:"RAJKOT",state:"GUJARAT",storelocations:[]},{ name:"RANCHI",value:"RANCHI",state:"JHARKHAND",storelocations:[]},
{ name:"ROHTAK",value:"ROHTAK",state:"HARYANA",storelocations:[]},{ name:"ROORKEE",value:"ROORKEE",state:"UTTARANCHAL",storelocations:[]},
{ name:"SAHARANPUR",value:"SAHARANPUR",state:"UTTAR PRADESH",storelocations:[]},{ name:"SALEM",value:"SALEM",state:"TAMIL NADU",storelocations:[]},
{ name:"SANGLI",value:"SANGLI",state:"MAHARASHTRA",storelocations:[]},{ name:"SHIMLA",value:"SHIMLA",state:"HIMACHAL PRADESH",storelocations:[]},
{ name:"SIKKIM",value:"SIKKIM",state:"SIKKIM",storelocations:[]},{ name:"SILIGURI",value:"SILIGURI",state:"WEST BENGAL",storelocations:[]},
{ name:"SOLAN",value:"SOLAN",state:"HIMACHAL PRADESH",storelocations:[]},{ name:"SOLAPUR",value:"SOLAPUR",state:"MAHARASHTRA",storelocations:[]},
{ name:"SURAT",value:"SURAT",state:"GUJARAT",storelocations:[]},{ name:"THANE",value:"THANE",state:"MAHARASHTRA",storelocations:[]},
{ name:"TRICHY",value:"TRICHY",state:"TAMIL NADU",storelocations:[]},{ name:"TRIVANDRUM",value:"TRIVANDRUM",state:"KERALA",storelocations:[]},
{ name:"UJJAIN",value:"UJJAIN",state:"MADHYA PRADESH",storelocations:[]},{ name:"VADODARA",value:"VADODARA",state:"GUJARAT",storelocations:[]},
{ name:"VAPI",value:"VAPI",state:"GUJARAT",storelocations:[]},{ name:"VARANASI",value:"VARANASI",state:"UTTAR PRADESH",storelocations:[]},
{ name:"VISAKHAPATNAM",value:"VISAKHAPATNAM",state:"ANDHRA PRADESH",storelocations:[]},
{ name:"ZIRAKPUR",value:"ZIRAKPUR",state:"PUNJAB",storelocations:[]}])

};
$(function(){
	ko.applyBindings(citiesDB);
	
});

